### ISSUE TITLE
demopylongstreamer binary crashing on ubuntu16.04

### ISSUE THREAD

**Issue by harendra247** [MattsProjects/pylon_gstreamer#19]
I was trying to make it work on Nvidia Tx2 but I could not succeeded, so thought of trying it on x86_64 (Ubuntu 16.04) and am facing the crash.
I am using the following libraries.
```
Gstreamer version : 1.8.3
Basler pylon lib version : 5.0.12

```
Below is the back trace . Let me know if more info needed.

```
(gdb) r
Starting program: /persistent/pylon_gstreamer/Samples/demopylongstreamer/demopylongstreamer -rescale 320 240 -parse gst-launch-1.0\ videotestsrc\ \!\ videoflip\ method=vertical-flip\ \!\ videoconvert\ \!\ autovideosink
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Press CTRL+C at any time to quit.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff18d9688 in ?? () from /opt/pylon5/lib64/libMathParser_gcc_v3_1_Basler_pylon.so
(gdb) bt
#0  0x00007ffff18d9688 in ?? () from /opt/pylon5/lib64/libMathParser_gcc_v3_1_Basler_pylon.so
#1  0x00007ffff7de76ba in call_init (l=<optimized out>, argc=argc@entry=6, argv=argv@entry=0x7fffffffdc48, env=env@entry=0x8224e0)
    at dl-init.c:72
#2  0x00007ffff7de77cb in call_init (env=0x8224e0, argv=0x7fffffffdc48, argc=6, l=<optimized out>) at dl-init.c:30
#3  _dl_init (main_map=main_map@entry=0x8526d0, argc=6, argv=0x7fffffffdc48, env=0x8224e0) at dl-init.c:120
#4  0x00007ffff7dec8e2 in dl_open_worker (a=a@entry=0x7fffffffcee0) at dl-open.c:575
#5  0x00007ffff7de7564 in _dl_catch_error (objname=objname@entry=0x7fffffffced0, errstring=errstring@entry=0x7fffffffced8, 
    mallocedp=mallocedp@entry=0x7fffffffcecf, operate=operate@entry=0x7ffff7dec4d0 <dl_open_worker>, args=args@entry=0x7fffffffcee0)
    at dl-error.c:187
#6  0x00007ffff7debda9 in _dl_open (file=0x852658 "/opt/pylon5/lib64/libpylon_TL_bcon-5.2.0.so", mode=-2147483390, 
    caller_dlopen=0x7ffff72c1cd8, nsid=-2, argc=<optimized out>, argv=<optimized out>, env=0x8224e0) at dl-open.c:660
#7  0x00007ffff5a45f09 in dlopen_doit (a=a@entry=0x7fffffffd110) at dlopen.c:66
#8  0x00007ffff7de7564 in _dl_catch_error (objname=0x62f120, errstring=0x62f128, mallocedp=0x62f118, operate=0x7ffff5a45eb0 <dlopen_doit>, 
    args=0x7fffffffd110) at dl-error.c:187
#9  0x00007ffff5a46571 in _dlerror_run (operate=operate@entry=0x7ffff5a45eb0 <dlopen_doit>, args=args@entry=0x7fffffffd110) at dlerror.c:163
#10 0x00007ffff5a45fa1 in __dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:87
#11 0x00007ffff72c1cd8 in ?? () from /opt/pylon5/lib64/libpylonbase-5.0.12.so
#12 0x00007ffff72bf1ce in ?? () from /opt/pylon5/lib64/libpylonbase-5.0.12.so
#13 0x00007ffff72bfe86 in Pylon::CTlFactory::InternalEnumerateTls(Pylon::TlInfoList&) () from /opt/pylon5/lib64/libpylonbase-5.0.12.so
#14 0x00007ffff72c017c in Pylon::CTlFactory::EnumerateTls(Pylon::TlInfoList&) () from /opt/pylon5/lib64/libpylonbase-5.0.12.so
#15 0x00007ffff72c1405 in Pylon::CTlFactory::EnumerateDevices(Pylon::DeviceInfoList&, Pylon::DeviceInfoList const&, bool) ()
   from /opt/pylon5/lib64/libpylonbase-5.0.12.so
#16 0x00007ffff72c0ba2 in Pylon::CTlFactory::InternalCreateDevice(Pylon::CDeviceInfo const&, GenICam_3_0_Basler_pylon_v5_0::gcstring_vector const&, bool) () from /opt/pylon5/lib64/libpylonbase-5.0.12.so
#17 0x00007ffff72c1735 in Pylon::CTlFactory::CreateFirstDevice(Pylon::CDeviceInfo const&) () from /opt/pylon5/lib64/libpylonbase-5.0.12.so
#18 0x000000000040c524 in CInstantCameraAppSrc::CInstantCameraAppSrc(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
#19 0x000000000040b4cd in main ()
```

**Comment by harendra247** [comment]
Upgraded to Basler Pylon lib version : 5.2.0 and crash got resolved.
